# Build stage
FROM node:22.20-slim AS builder

WORKDIR /app

COPY package.json ./
COPY index.html ./
COPY vite.config.js ./
COPY src ./src

ARG API_BASE_URL
ENV VITE_API_BASE=${API_BASE_URL}
ARG COGNITO_USER_POOL_DOMAIN
ENV VITE_COGNITO_USER_POOL_DOMAIN=${COGNITO_USER_POOL_DOMAIN}
ARG COGNITO_CLIENT_ID
ENV VITE_COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
ARG COGNITO_REDIRECT_SIGNUP_URI
ENV VITE_COGNITO_REDIRECT_SIGNUP_URI=${COGNITO_REDIRECT_SIGNUP_URI}
ARG COGNITO_REDIRECT_LOGIN_URI
ENV VITE_COGNITO_REDIRECT_LOGIN_URI=${COGNITO_REDIRECT_LOGIN_URI}
ARG COGNITO_REDIRECT_LOGOUT_URI
ENV VITE_COGNITO_REDIRECT_LOGOUT_URI=${COGNITO_REDIRECT_LOGOUT_URI}

RUN npm install && npm run build

# Production stage
FROM nginx:alpine

# Copy built frontend assets
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy custom nginx config (optional)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
